### ISSUE TITLE
Can not run avcaesar.py with python2

### ISSUE THREAD

**Issue by alex-bender** [MalwareLu/avcaesar-api-python-driver#1]
```
$ avcaesar.py
Traceback (most recent call last):
  File "/usr/local/bin/avcaesar.py", line 9, in <module>
    load_entry_point('avcaesar-api==1.0.3', 'console_scripts', 'avcaesar.py')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/avcaesar_api-1.0.3-py2.7.egg/avcaesar_api/__main__.py", line 45
    ceil(analysis_history['total']/float(analysis_history['per_page'])), sep='')
                                                                            ^
SyntaxError: invalid syntax
```

**Comment by defane** [comment]
I just added a support for python2. Enjoy!
